name: Build and Release CRX

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    check-version:
        runs-on: ubuntu-latest
        outputs:
            should_release: ${{ steps.check.outputs.should_release }}
            next_version: ${{ steps.check.outputs.next_version }}
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

            - name: Check manifest version vs latest tag
              id: check
              run: |
                  node scripts/check-version.mjs
              shell: bash

    build-crx:
        needs: check-version
        if: needs.check-version.outputs.should_release == 'true'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-tags: true

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

            - name: Decode private key
              run: |
                  echo "$CHROME_EXTENSION_PRIVATE_KEY_B64" | base64 -d > chrome-extension.pem
              env:
                  CHROME_EXTENSION_PRIVATE_KEY_B64: ${{ secrets.CHROME_EXTENSION_PRIVATE_KEY_B64 }}

            - name: Install crx packer
              run: npm install -g crx

            - name: Build CRX
              run: |
                  mkdir -p dist
                  crx pack . -p chrome-extension.pem -o dist/tailgunner-for-tailwind.crx

            - name: Tag commit
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git tag ${{ needs.check-version.outputs.next_version }}
                  git push origin ${{ needs.check-version.outputs.next_version }}

            - name: Upload release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ needs.check-version.outputs.next_version }}
                  files: dist/tailgunner-for-tailwind.crx
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
